import type { Metadata } from "next";
export const metadata: Metadata={title:"Projects",description:"Selected IT, AI and operational software projects by Willem Grobler."};
const items=[
["Grovoris","An AI-assisted IT service-management platform concept covering ticketing, CMDB, asset discovery, service health, knowledge and controlled technician workflows.","Next.js · TypeScript · PostgreSQL · Prisma · AI-assisted workflows"],
["CareerPilot AI","A career application assistant designed to score roles, tailor truthful ATS resumes and cover letters, track applications and keep a human approval step before submission.","Next.js · TypeScript · PostgreSQL · AI-assisted document generation"],
["Knowledge Capture","A standalone application concept for turning resolved IT support tickets into reviewed, searchable knowledge articles.","Knowledge management · Review workflow · Search"],
["Remote IT Engineer","An infrastructure analysis and reporting concept covering Windows Event Logs, backups, Active Directory health, virtualization and Microsoft 365.","Windows infrastructure · PowerShell · Reporting"],
["Quality Operations Dashboard","A read-only quality dashboard for calibration status, NCR visibility and approved supplier information.","Next.js · Prisma · Excel data ingestion · Operational reporting"]];
export default function Projects(){return <main className="shell"><header className="nav"><a className="brand" href="/">WG</a><nav><a href="/">Home</a><a href="/resume/">Resume</a></nav></header><section className="pageHero"><div className="eyebrow">PROJECT PORTFOLIO</div><h1>Practical tools built around real operational problems.</h1><p className="lead">These projects are not presented as a claim that I am a full-time software developer. They demonstrate how I use modern tooling and AI to solve infrastructure, service-management and operational problems.</p></section><section className="pageBody">{items.map(([n,b,t])=><article className="project" key={n}><h4>{n}</h4><div><p>{b}</p><div className="tag">{t}</div></div></article>)}<div className="actions"><a className="secondary" href="https://github.com/wgrobler72" target="_blank" rel="noreferrer">View GitHub</a></div></section></main>}
