const metrics=[["20+","Years in IT"],["120","Microsoft 365 Users"],["39","Sites Supported"],["12","Windows Servers"]];
const expertise=[["Microsoft Cloud","Microsoft 365, Azure, Exchange Online, Teams, SharePoint Online, OneDrive"],["Identity & Endpoint","Entra ID, Intune, MFA, Conditional Access, Microsoft Defender"],["Infrastructure","Windows Server, Active Directory, Group Policy, Hyper-V, VMware"],["Backup & DR","Veeam, Backup Exec, recovery planning and disaster recovery"],["Networking & Security","TCP/IP, VPN, VLANs, Cisco, Sophos firewalls"],["Enterprise Systems","SYSPRO, Teamcenter, CATIA, Jarrison and engineering systems"]];
const experience=[
{period:"2023 — Present",role:"IT Manager / Senior IT Administrator",company:"Paramount Aerospace Industries",points:["Lead IT operations supporting approximately 110 users across business, engineering and manufacturing functions.","Administer approximately 120 Microsoft 365 users across Exchange Online, Teams, SharePoint Online, OneDrive, Entra ID, Intune and Defender.","Manage 12 Windows Servers and 10 Hyper-V virtual machines.","Administer MFA, Conditional Access, backup and recovery, networking and business-critical systems."]},
{period:"2019 — 2023",role:"IT Engineer",company:"CHM Vuwani First Technology",points:["Delivered Microsoft cloud and infrastructure services in an MSP environment supporting estates of approximately 20 to 600 users.","Administered approximately 21 Windows Servers plus VMware and Hyper-V environments.","Performed Microsoft 365 and Azure migrations, including work for the Limpopo Department of Health and Social Development."]},
{period:"2015 — 2019",role:"IT Technical Lead",company:"IT Masters",points:["Administered Windows Server, Office 365, Hyper-V, VMware, firewalls and backup solutions across MSP customer environments.","Provided technical leadership to a team of approximately 10 people."]},
{period:"2014 — 2015",role:"Helpdesk Manager & Technical Lead",company:"Enabling Solutions",points:["Managed IT support for approximately 450 Limpopo Department of Health users across 39 sites.","Supported distributed infrastructure with typically 2 to 8 servers per site."]}
];
const projects=[["Grovoris","AI-assisted IT service-management platform focused on ticketing, CMDB, discovery and knowledge workflows."],["CareerPilot AI","AI-assisted career platform for job matching, CV tailoring, cover letters and controlled application workflows."],["Knowledge Capture","Converts resolved IT incidents into reviewed, searchable knowledge articles."],["Remote IT Engineer","Infrastructure analysis and reporting concept for Windows, Microsoft 365, backups and operational health."],["Quality Operations Dashboard","Read-only quality dashboard for calibration, NCR and supplier-status visibility."]];
const certs=["MCSE","MCSA","VMware VCP6-DCV","ITIL Foundation","CompTIA Network+","CompTIA A+","Cyberoam CCNSP","Certified Novell Administrator"];
function Nav(){return <header className="nav"><a className="brand" href="/">WG</a><nav><a href="/#about">About</a><a href="/#experience">Experience</a><a href="/#case-studies">Case Studies</a><a href="/projects/">Projects</a><a href="/resume/">Resume</a><a href="/#contact">Contact</a></nav></header>}
export default function Home(){return <main className="shell"><Nav/><section className="hero"><div className="heroGrid"><div><div className="eyebrow">IT INFRASTRUCTURE · MICROSOFT CLOUD · OPERATIONS</div><h1>Willem Grobler</h1><h2>IT Infrastructure Manager <span>·</span> Microsoft 365 <span>·</span> Azure <span>·</span> Windows Server</h2><p className="lead">More than 20 years of experience administering, improving and recovering enterprise IT environments across aerospace, manufacturing, government and managed services.</p><div className="actions"><a className="primary" href="/resume/">View Resume</a><a className="secondary" href="/#case-studies">View Case Studies</a></div></div><img className="avatar" src="https://avatars.githubusercontent.com/u/45467329?v=4" alt="Willem Grobler professional profile" /></div><div className="metrics">{metrics.map(([n,l])=><div className="metric" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
<section id="about" className="section"><div className="sectionLabel">ABOUT</div><div className="twoCol"><h3>Hands-on infrastructure experience with operational leadership.</h3><div><p>I’m an IT infrastructure and operations professional with a career spanning government, MSP, aerospace and manufacturing environments.</p><p>My work combines hands-on administration with leadership. I still troubleshoot difficult incidents, while also managing budgets, staff, infrastructure lifecycle decisions, Microsoft cloud services and business-critical systems.</p><p>I’m particularly interested in senior infrastructure, Microsoft cloud and IT operations roles where practical experience, judgement and reliability matter.</p></div></div></section>
<section className="section alt"><div className="sectionLabel">TECHNICAL EXPERTISE</div><div className="grid3">{expertise.map(([t,b])=><article className="card" key={t}><h4>{t}</h4><p>{b}</p></article>)}</div></section>
<section id="experience" className="section"><div className="sectionLabel">EXPERIENCE</div><h3>Career progression</h3><div className="timeline">{experience.map(e=><article className="job" key={e.company}><div className="period">{e.period}</div><div><h4>{e.role}</h4><div className="company">{e.company}</div><ul>{e.points.map(p=><li key={p}>{p}</li>)}</ul></div></article>)}</div></section>
<section id="case-studies" className="section alt"><div className="sectionLabel">CASE STUDIES</div><h3>Evidence behind the resume</h3><div className="grid2"><article className="case"><div className="tag">CLOUD MIGRATION</div><h4>Microsoft 365 & Azure Migration</h4><p>Migration work for the Limpopo Department of Health and Social Development involving cloud administration, identity, planning and operational support.</p><a href="/case-studies/m365-azure/">Read case study →</a></article><article className="case"><div className="tag">DISASTER RECOVERY</div><h4>Department-Wide Recovery</h4><p>Recovery of an entire department from enterprise backups following a major infrastructure failure.</p><a href="/case-studies/disaster-recovery/">Read case study →</a></article><article className="case"><div className="tag">MULTI-SITE OPERATIONS</div><h4>39-Site Government Support</h4><p>Support operations for approximately 450 users across 39 geographically distributed sites.</p></article><article className="case"><div className="tag">AEROSPACE IT</div><h4>Business-Critical Infrastructure</h4><p>Microsoft 365, Windows Server, Hyper-V, backup and engineering systems in an aerospace and manufacturing environment.</p></article></div></section>
<section id="projects" className="section"><div className="sectionLabel">PROJECTS</div><h3>Building with AI and modern tooling</h3><div className="projectList">{projects.map(([n,b])=><article className="project" key={n}><h4>{n}</h4><p>{b}</p></article>)}</div><div className="actions"><a className="secondary" href="/projects/">View project portfolio</a></div></section>
<section className="section alt"><div className="sectionLabel">CERTIFICATIONS</div><div className="chips">{certs.map(c=><span key={c}>{c}</span>)}</div></section>
<section id="contact" className="section contact"><div className="sectionLabel">CONTACT</div><h3>Let’s connect.</h3><p>For senior IT infrastructure, Microsoft cloud and IT operations opportunities.</p><div className="actions"><a className="primary" href="https://www.linkedin.com/in/willem-grobler-b17746347" target="_blank" rel="noreferrer">LinkedIn</a><a className="secondary" href="https://github.com/wgrobler72" target="_blank" rel="noreferrer">GitHub</a></div></section><footer><span>© 2026 Willem Grobler</span><span>willemgrobler.tech</span></footer></main>}
